"""
alerts.py - Send email and Slack alerts for high-risk suppliers.
Configure via environment variables:
  - SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, ALERT_EMAIL_TO
  - SLACK_WEBHOOK_URL
"""

import os
import smtplib
import requests
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import pandas as pd
import streamlit as st


def build_alert_message(supplier: dict) -> str:
    """Build a plain-text alert message for a high-risk supplier."""
    return f"""
🚨 HIGH RISK SUPPLIER ALERT

Supplier Name : {supplier.get('supplier_name', 'N/A')}
Location      : {supplier.get('city', 'N/A')}, {supplier.get('country', 'N/A')}
Tier          : {supplier.get('tier', 'N/A')}
Risk Score    : {supplier.get('risk_score', 0):.1f} / 100
Risk Level    : {supplier.get('risk_level', 'N/A')}

Event Summary:
{supplier.get('event_summary', 'No summary available.')}

---
Generated by Supplier Risk Dashboard
""".strip()


def send_email_alert(supplier: dict) -> bool:
    """
    Send an email alert for a high-risk supplier.
    Reads SMTP config from environment variables.
    Returns True if successful.
    """
    smtp_host = os.getenv("SMTP_HOST", "")
    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASS", "")
    alert_to = os.getenv("ALERT_EMAIL_TO", "")

    if not all([smtp_host, smtp_user, smtp_pass, alert_to]):
        return False

    subject = f"⚠️ High Risk Supplier: {supplier.get('supplier_name', 'Unknown')} (Score: {supplier.get('risk_score', 0):.0f})"
    body = build_alert_message(supplier)

    msg = MIMEMultipart()
    msg["From"] = smtp_user
    msg["To"] = alert_to
    msg["Subject"] = subject
    msg.attach(MIMEText(body, "plain"))

    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.send_message(msg)
        return True
    except Exception as e:
        st.error(f"Email alert failed: {e}")
        return False


def send_slack_alert(supplier: dict) -> bool:
    """
    Send a Slack alert using a webhook URL.
    Set SLACK_WEBHOOK_URL environment variable.
    Returns True if successful.
    """
    webhook_url = os.getenv("SLACK_WEBHOOK_URL", "")
    if not webhook_url:
        return False

    message = build_alert_message(supplier)
    payload = {
        "text": message,
        "username": "SupplierRiskBot",
        "icon_emoji": ":warning:",
    }

    try:
        response = requests.post(webhook_url, json=payload, timeout=10)
        return response.status_code == 200
    except Exception as e:
        st.error(f"Slack alert failed: {e}")
        return False


def dispatch_alerts(suppliers_df: pd.DataFrame) -> int:
    """
    Send alerts for all high-risk suppliers (risk_score > 50).
    Returns number of alerts sent.
    """
    high_risk = suppliers_df[suppliers_df["risk_score"] > 50]
    sent = 0

    for _, row in high_risk.iterrows():
        supplier = row.to_dict()
        email_sent = send_email_alert(supplier)
        slack_sent = send_slack_alert(supplier)
        if email_sent or slack_sent:
            sent += 1

    return sent
